provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  filter-tweets:
    lang: go
    handler: ./filter-tweets
    image: alexellis2/filter-tweets:2019-07-24
    labels:
      com.openfaas.scale.zero: false
    environment:
      write_debug: true
      read_debug: true
      combine_output: false
    secrets:
      - tweet-filter-secrets

