provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  filter-tweets:
    lang: go
    handler: ./filter-tweets
    image: alexellis2/filter-tweets:2018-04-18
    labels:
      com.openfaas.scale.zero: false
    secrets:
      - tweet-filter-secrets
